# -*- coding: utf-8 -*-
"""Sıfırı Taşı.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n662qM1rtagTz6DWVzYJX7dgfKtiBLfi
"""

mylist = [2,4,1,6,4,0,0]
print(mylist)
mylist.pop(6)

mylist.pop(5)
mylist.insert(0,0)

mylist.insert(1,0)
print(mylist)