# -*- coding: utf-8 -*-
"""Tek Sayı Güncelleme.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pb-LrTUjwUx0PkK-RVewVVoXVKwtoFe2
"""

sayi1 = str(input("SAYILARI GİRİNİZ"))
listem=[0,1,2,3,4,5,6,7,8,9]
print ("DİZİNİN EN BÜYÜK TEK SAYISI: ",max(listem))